### ISSUE TITLE
Write up investigation of Artificial Neural Networks

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Medi-App#3]
Write up an investigation of ANN using the following guide:

1. Explain the algorithm simply, using diagrams where possible (seriously, as short as you can)
1. Discuss related work and relevant literature (references) to the algorithm that relate to our project objective (the state-of-the-art, art being the algorithm in practice)
1. Discuss why the particular algorithm is a strong contender to provide a best solution to the project objective

Since our final report is to be a maximum of 8 pages for our group of 4, **write the investigation aiming for about 1 page in length** (give or take half a page). [Use APA format writing!](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/general_format.html)

Put the writing in a Google Doc and share the **read-only link** as a comment on this issue.

**Comment by mansiPaTeLL** [comment]
Please find the investigation for review [here](https://docs.google.com/document/d/1sdAmU6DnvibdFUO0FVihl0HNp7SbxCaGhckeUMGBMIo/edit?usp=sharing). 

Find the neural network python library: [https://github.com/aigamedev/scikit-neuralnetwork](https://github.com/aigamedev/scikit-neuralnetwork)

**Comment by holtzmak** [comment]
This looks pretty good. It's hard to explain ANN.

I'm not able to make comments or add suggestions to the document. Could you update the link to allow comments?

**Comment by mansiPaTeLL** [comment]
@holtzmak https://docs.google.com/document/d/1sdAmU6DnvibdFUO0FVihl0HNp7SbxCaGhckeUMGBMIo/edit?usp=sharing
You can use this link to comment.

**Comment by holtzmak** [comment]
I made a few suggestions to the APA format, and I have a question about your last sentence that you'll see in the Google doc.

**Comment by mansiPaTeLL** [comment]
@holtzmak I made the changes that you have addressed. So for the predicate value, I mean to say "Weights " for the symptoms. I have made changed to "predicate value" to "weights"
