### ISSUE TITLE
Write up investigation of k-means Clustering

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Medi-App#4]
Write up an investigation of k-means using the following guide:

1. Explain the algorithm simply, using diagrams where possible (seriously, as short as you can)
1. Discuss related work and relevant literature (references) to the algorithm that relate to our project objective (the state-of-the-art, art being the algorithm in practice)
1. Discuss why the particular algorithm is a strong contender to provide a best solution to the project objective

Since our final report is to be a maximum of 8 pages for our group of 4, **write the investigation aiming for about 1 page in length** (give or take half a page). [Use APA format writing!](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/general_format.html)

Put the writing in a Google Doc and share the **read-only link** as a comment on this issue.

**Comment by AliR19** [comment]
The investigation link for review is here
The python library that uses the algorithm is https://scikit-learn.org/stable/

**Comment by holtzmak** [comment]
Hi Ali, I'm not able to make comments or add suggestions to the document. Could you update the link to allow comments?

**Comment by AliR19** [comment]
I updated it

**Comment by holtzmak** [comment]
This is a good first draft. I made a few minor suggestions with spelling mistakes and formatting. 

The only major thing I found was that your last paragraph was repeating the previous paragraphs. Instead, what we want are the results of your article (Vijayalakshmi, 2020) that made k-means a good choice for disease-symptom diagnosing (our project).

Please update the last paragraph accordingly.

**Comment by AliR19** [comment]
Have did required changes.

**Comment by holtzmak** [comment]
Your last paragraph is much better now :). 

Do you think k-means clustering is our best algorithm for the project? I am not sure because I think that k-means would group the symptoms for a disease, but not predict the disease. How do you think k-means clustering would tell us which disease is most likely? 

For example, I know that a Bayes net would tell us the most likely disease if we use [pomegranate as explained here](https://pomegranate.readthedocs.io/en/latest/BayesianNetwork.html) because the `model.predict` function returns the disease most likely and we can use `model.probability` to find the likeliness of that disease happening. Is there something in the scikit-learn module that will predict with k-means what the disease is?

**Comment by AliR19** [comment]
I didn't find any prediction function similar to Bayes net in k-means. The main goal of k-means clustering is to find groups of
data which is unlabeled and after that functions are clustered based on feature similarity by using Euclidian distance
formula. However, an (enhanced k-means) k-means with a combination of some other supervised learning method would be able to do it
