### ISSUE TITLE
Create the program dataset component

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Medi-App#8]
Gather from [Kaggle](https://www.kaggle.com/datasets?search=symptoms) some dataset with symptoms and illnesses that were sampled. 

_You'll want to use samples with observed symptoms and diseases. You'll also want to have some dataset that is fairly legitimate (for example, if the discussion on the dataset suggests that the data may not be legit, don't use it)_

We don't need or care for personal information in the dataset, so if you find a good one with such data, cut out the columns that represent personal data. 

We'll be using the data for our probability tables, so either the dataset should come with probabilities or we need to generate the probabilities from the dataset. This means we count the joint probability like what I did for the Bayes' net investigation, and end up with a format like the table you see in this [pomegranate example](https://pomegranate.readthedocs.io/en/latest/BayesianNetwork.html).

Since most datasets are CSV, we should use the CSV python libraries out there to turn the file into a list of lists like the pomegranate example above. We'll also want to save our data to CSV when we've made the tables so that the next time the program runs, it has the data in CSV ready to pull and use.

The data structure of the symptoms and illnesses while the program is running should be discussed with the assignee of # 5.

A finished product should have: code that does the above and some simple [unit tests](https://docs.python.org/3/library/unittest.html). _The unit tests should be for confirming we're able to transform the CSV into our own data structure_

_The unit tests could be written first and given to the assignee of #5 as they would have the expected data structure!_

**Comment by holtzmak** [comment]
This looks like the best data set to use: https://www.kaggle.com/kaushil268/disease-prediction-using-machine-learning?select=Training.csv

It's extensive, has symptoms as true/false, or present/not present, and lists their prognosis.

We could probably use excel to just clean up the data (i.e. change the 0s of the columns into something like "no itching" instead) and then just write python code that will take the csv and make a lists of lists (for example) from the csv. We then avoid having to make any special code if we just assume the csv file is in the format we need for our algorithms, because it would fail to work otherwise.

**Comment by holtzmak** [comment]
There exists a built-in python module for reading from csv, it's so easy I could cry: https://docs.python.org/3/library/csv.html.

An easy-to-read example is here https://docs.python.org/3/library/csv.html.

**Comment by holtzmak** [comment]
Cleaned datasets with conditional probability tables are [here (symptoms)](https://docs.google.com/spreadsheets/d/1M6xo2K7Av9598XGMydYh-WZ1zEtkimZqxZo2aRCP2lQ/edit?usp=sharing) and [here (prognosis)](https://docs.google.com/spreadsheets/d/1ttMf_sUci0GV2_Vlsd8LQdJ8VbulGxGG1n7vnDWGcLg/edit?usp=sharing).

**Comment by mansiPaTeLL** [comment]
@holtzmak Please look this repository [readCSVfile](https://github.com/mansiPaTeLL/readCSVfile). I didn't create PR for this as I do not want to mess up with our repository.

**Comment by holtzmak** [comment]
> @holtzmak Please look this repository [readCSVfile](https://github.com/mansiPaTeLL/readCSVfile). I didn't create PR for this as I do not want to mess up with our repository.

I see what you mean, there's quite quite a bit going on there. We can work together to figure out how to merge just what we need into this repo.

This is well done, I do have some questions and suggestions but they would be best discussed over zoom or similar. Thank you very much for your hard work on this!
